name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Run Tests
        id: go_test
        run: go test -v ./...

      # Conditional step: Create a new tag if tests pass
      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.OG_RELEASE_TAG_UPDATE }}
          release_branches: main
          tag_prefix: v

